version: '3.8'

services:
  msckf_vio:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        USERNAME: dev9
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    image: zhuyueying/msckf_vio:kinetic-16.04-opencv3
    container_name: msckf_vio
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ${HOME}/Algs/msckf:/ws
      - ${HOME}/Algs/msckf/Results_msckf:/ws/results
      - ${HOME}/Algs/svo2/OIVIO_svo2:/datasets/OIVIO:ro
      - ${HOME}/Algs/svo2/MIN3D_svo2:/datasets/MIN3D:ro
      - ${HOME}/Datasets/DARPA-CERBERUS/anymal_3:/datasets/CERBERUS:ro
    shm_size: "2g"
    tty: true
    stdin_open: true
    command: bash -lc "sleep infinity"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]